/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnatest_JNATest */

#ifndef _Included_jnatest_JNATest
#define _Included_jnatest_JNATest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
