/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnatest_JNATest_MyLibrary_callback */

#ifndef _Included_jnatest_JNATest_MyLibrary_callback
#define _Included_jnatest_JNATest_MyLibrary_callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
