/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnatest_JNATest_CLibrary */

#ifndef _Included_jnatest_JNATest_CLibrary
#define _Included_jnatest_JNATest_CLibrary
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
